services:
  tarantool:
    image: tarantool/tarantool:2.11.5
    container_name: kostjc-tarantool
    environment:
      TARANTOOL_USER_NAME: "userT"
      TARANTOOL_USER_PASSWORD: "passT"
      TT_READAHEAD: '1632000' # 10x
      TT_VINYL_MEMORY: '268435456' # 20x
      TT_VINYL_CACHE: '2684354560' # 20x
      TT_NET_MSG_MAX: '76800' # 100x
      TT_MEMTX_MEMORY: '268435456' # 1x
      TT_VINYL_PAGE_SIZE: '8192' # 1x
      TT_FORCE_RECOVERY: 'true'
    volumes:
      - ./_tmpdb/var_lib_tarantool:/var/lib/tarantool
    ports:
      - "3303:3301"

  clickhouse:
    image: clickhouse/clickhouse-server:23.11.2.11
    container_name: kostjc-clickhouse
    ports:
      - "8125:8123"
      - "9002:9000"
    environment:
      CLICKHOUSE_USER: "userC"
      CLICKHOUSE_PASSWORD: "passC"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./_tmpdb/var_lib_clickhouse:/var/lib/clickhouse

  mailhog:
    image: mailhog/mailhog
    container_name: kostjc-mailhog
    ports:
      - "1027:1025"
      - "8027:8025"