package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"kostjc/domain"
)

var allCommands = []string{
	domain.UserLogoutAction,
	domain.UserProfileAction,
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
