package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"kostjc/domain"
)

var allCommands = []string{
	domain.GuestLoginAction,
	domain.GuestRegisterAction,
	domain.GuestResendVerificationEmailAction,
	domain.GuestResetPasswordAction,
	domain.GuestVerifyEmailAction,
	domain.UserBuildingAction,
	domain.UserFacilityAction,
	domain.UserLocationAction,
	domain.UserLogoutAction,
	domain.UserProfileAction,
	domain.UserSessionKillAction,
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
