package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"kostjc/domain"
)

var allCommands = []string{
	domain.AdminBookingAction,
	domain.AdminBuildingAction,
	domain.AdminFacilityAction,
	domain.AdminLocationAction,
	domain.AdminPaymentAction,
	domain.AdminRoomAction,
	domain.AdminStockAction,
	domain.AdminTenantsAction,
	domain.AdminUsersManagementAction,
	domain.GuestLoginAction,
	domain.GuestRegisterAction,
	domain.GuestResendVerificationEmailAction,
	domain.GuestResetPasswordAction,
	domain.GuestVerifyEmailAction,
	domain.StaffBookingAction,
	domain.UserLogoutAction,
	domain.UserProfileAction,
	domain.UserSessionKillAction,
	domain.UserSessionsActiveAction,
	domain.UserUpdateProfileAction,
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
