package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"github.com/gofiber/fiber/v2"

	"kostjc/domain"
)

func ApiRoutes(fw *fiber.App, d *domain.Domain) {

	// AdminBooking
	fw.Post("/"+domain.AdminBookingAction, func(c *fiber.Ctx) error {
		in := domain.AdminBookingIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminBookingAction); err != nil {
			return nil
		}
		out := d.AdminBooking(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminBookingLogs
	fw.Post("/"+domain.AdminBookingLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminBookingLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminBookingLogsAction); err != nil {
			return nil
		}
		out := d.AdminBookingLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminBorrowedUtensilLogs
	fw.Post("/"+domain.AdminBorrowedUtensilLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminBorrowedUtensilLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminBorrowedUtensilLogsAction); err != nil {
			return nil
		}
		out := d.AdminBorrowedUtensilLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminBorrowedUtensils
	fw.Post("/"+domain.AdminBorrowedUtensilsAction, func(c *fiber.Ctx) error {
		in := domain.AdminBorrowedUtensilsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminBorrowedUtensilsAction); err != nil {
			return nil
		}
		out := d.AdminBorrowedUtensils(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminBuilding
	fw.Post("/"+domain.AdminBuildingAction, func(c *fiber.Ctx) error {
		in := domain.AdminBuildingIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminBuildingAction); err != nil {
			return nil
		}
		out := d.AdminBuilding(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminBuildingLogs
	fw.Post("/"+domain.AdminBuildingLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminBuildingLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminBuildingLogsAction); err != nil {
			return nil
		}
		out := d.AdminBuildingLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminFacility
	fw.Post("/"+domain.AdminFacilityAction, func(c *fiber.Ctx) error {
		in := domain.AdminFacilityIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminFacilityAction); err != nil {
			return nil
		}
		out := d.AdminFacility(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminFacilityLogs
	fw.Post("/"+domain.AdminFacilityLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminFacilityLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminFacilityLogsAction); err != nil {
			return nil
		}
		out := d.AdminFacilityLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminLaundry
	fw.Post("/"+domain.AdminLaundryAction, func(c *fiber.Ctx) error {
		in := domain.AdminLaundryIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminLaundryAction); err != nil {
			return nil
		}
		out := d.AdminLaundry(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminLaundryLogs
	fw.Post("/"+domain.AdminLaundryLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminLaundryLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminLaundryLogsAction); err != nil {
			return nil
		}
		out := d.AdminLaundryLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminLocation
	fw.Post("/"+domain.AdminLocationAction, func(c *fiber.Ctx) error {
		in := domain.AdminLocationIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminLocationAction); err != nil {
			return nil
		}
		out := d.AdminLocation(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminLocationLogs
	fw.Post("/"+domain.AdminLocationLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminLocationLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminLocationLogsAction); err != nil {
			return nil
		}
		out := d.AdminLocationLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminMenu
	fw.Post("/"+domain.AdminMenuAction, func(c *fiber.Ctx) error {
		in := domain.AdminMenuIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminMenuAction); err != nil {
			return nil
		}
		out := d.AdminMenu(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminMenuLogs
	fw.Post("/"+domain.AdminMenuLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminMenuLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminMenuLogsAction); err != nil {
			return nil
		}
		out := d.AdminMenuLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminPayment
	fw.Post("/"+domain.AdminPaymentAction, func(c *fiber.Ctx) error {
		in := domain.AdminPaymentIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminPaymentAction); err != nil {
			return nil
		}
		out := d.AdminPayment(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminPaymentLogs
	fw.Post("/"+domain.AdminPaymentLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminPaymentLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminPaymentLogsAction); err != nil {
			return nil
		}
		out := d.AdminPaymentLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminRoom
	fw.Post("/"+domain.AdminRoomAction, func(c *fiber.Ctx) error {
		in := domain.AdminRoomIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminRoomAction); err != nil {
			return nil
		}
		out := d.AdminRoom(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminRoomLogs
	fw.Post("/"+domain.AdminRoomLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminRoomLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminRoomLogsAction); err != nil {
			return nil
		}
		out := d.AdminRoomLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminSale
	fw.Post("/"+domain.AdminSaleAction, func(c *fiber.Ctx) error {
		in := domain.AdminSaleIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminSaleAction); err != nil {
			return nil
		}
		out := d.AdminSale(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminSaleLogs
	fw.Post("/"+domain.AdminSaleLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminSaleLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminSaleLogsAction); err != nil {
			return nil
		}
		out := d.AdminSaleLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminSettingFixInconsistencies
	fw.Post("/"+domain.AdminSettingFixInconsistenciesAction, func(c *fiber.Ctx) error {
		in := domain.AdminSettingFixInconsistenciesIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminSettingFixInconsistenciesAction); err != nil {
			return nil
		}
		out := d.AdminSettingFixInconsistencies(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminSettings
	fw.Post("/"+domain.AdminSettingsAction, func(c *fiber.Ctx) error {
		in := domain.AdminSettingsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminSettingsAction); err != nil {
			return nil
		}
		out := d.AdminSettings(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminStock
	fw.Post("/"+domain.AdminStockAction, func(c *fiber.Ctx) error {
		in := domain.AdminStockIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminStockAction); err != nil {
			return nil
		}
		out := d.AdminStock(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminStockLogs
	fw.Post("/"+domain.AdminStockLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminStockLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminStockLogsAction); err != nil {
			return nil
		}
		out := d.AdminStockLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminTenantLogs
	fw.Post("/"+domain.AdminTenantLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminTenantLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminTenantLogsAction); err != nil {
			return nil
		}
		out := d.AdminTenantLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminTenants
	fw.Post("/"+domain.AdminTenantsAction, func(c *fiber.Ctx) error {
		in := domain.AdminTenantsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminTenantsAction); err != nil {
			return nil
		}
		out := d.AdminTenants(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminUserLogs
	fw.Post("/"+domain.AdminUserLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminUserLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminUserLogsAction); err != nil {
			return nil
		}
		out := d.AdminUserLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminUsersManagement
	fw.Post("/"+domain.AdminUsersManagementAction, func(c *fiber.Ctx) error {
		in := domain.AdminUsersManagementIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminUsersManagementAction); err != nil {
			return nil
		}
		out := d.AdminUsersManagement(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminWifiDevice
	fw.Post("/"+domain.AdminWifiDeviceAction, func(c *fiber.Ctx) error {
		in := domain.AdminWifiDeviceIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminWifiDeviceAction); err != nil {
			return nil
		}
		out := d.AdminWifiDevice(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// AdminWifiDeviceLogs
	fw.Post("/"+domain.AdminWifiDeviceLogsAction, func(c *fiber.Ctx) error {
		in := domain.AdminWifiDeviceLogsIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.AdminWifiDeviceLogsAction); err != nil {
			return nil
		}
		out := d.AdminWifiDeviceLogs(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// GuestLogin
	fw.Post("/"+domain.GuestLoginAction, func(c *fiber.Ctx) error {
		in := domain.GuestLoginIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.GuestLoginAction); err != nil {
			return nil
		}
		out := d.GuestLogin(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// GuestRegister
	fw.Post("/"+domain.GuestRegisterAction, func(c *fiber.Ctx) error {
		in := domain.GuestRegisterIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.GuestRegisterAction); err != nil {
			return nil
		}
		out := d.GuestRegister(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// GuestResendVerificationEmail
	fw.Post("/"+domain.GuestResendVerificationEmailAction, func(c *fiber.Ctx) error {
		in := domain.GuestResendVerificationEmailIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.GuestResendVerificationEmailAction); err != nil {
			return nil
		}
		out := d.GuestResendVerificationEmail(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// GuestResetPassword
	fw.Post("/"+domain.GuestResetPasswordAction, func(c *fiber.Ctx) error {
		in := domain.GuestResetPasswordIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.GuestResetPasswordAction); err != nil {
			return nil
		}
		out := d.GuestResetPassword(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// GuestVerifyEmail
	fw.Post("/"+domain.GuestVerifyEmailAction, func(c *fiber.Ctx) error {
		in := domain.GuestVerifyEmailIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.GuestVerifyEmailAction); err != nil {
			return nil
		}
		out := d.GuestVerifyEmail(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// StaffBooking
	fw.Post("/"+domain.StaffBookingAction, func(c *fiber.Ctx) error {
		in := domain.StaffBookingIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.StaffBookingAction); err != nil {
			return nil
		}
		out := d.StaffBooking(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// StaffMissingDataReport
	fw.Post("/"+domain.StaffMissingDataReportAction, func(c *fiber.Ctx) error {
		in := domain.StaffMissingDataReportIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.StaffMissingDataReportAction); err != nil {
			return nil
		}
		out := d.StaffMissingDataReport(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// StaffOccupancyReport
	fw.Post("/"+domain.StaffOccupancyReportAction, func(c *fiber.Ctx) error {
		in := domain.StaffOccupancyReportIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.StaffOccupancyReportAction); err != nil {
			return nil
		}
		out := d.StaffOccupancyReport(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// StaffPricePerDayReport
	fw.Post("/"+domain.StaffPricePerDayReportAction, func(c *fiber.Ctx) error {
		in := domain.StaffPricePerDayReportIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.StaffPricePerDayReportAction); err != nil {
			return nil
		}
		out := d.StaffPricePerDayReport(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// StaffRevenueReport
	fw.Post("/"+domain.StaffRevenueReportAction, func(c *fiber.Ctx) error {
		in := domain.StaffRevenueReportIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.StaffRevenueReportAction); err != nil {
			return nil
		}
		out := d.StaffRevenueReport(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// StaffSales
	fw.Post("/"+domain.StaffSalesAction, func(c *fiber.Ctx) error {
		in := domain.StaffSalesIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.StaffSalesAction); err != nil {
			return nil
		}
		out := d.StaffSales(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// StaffWifiDeviceReport
	fw.Post("/"+domain.StaffWifiDeviceReportAction, func(c *fiber.Ctx) error {
		in := domain.StaffWifiDeviceReportIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.StaffWifiDeviceReportAction); err != nil {
			return nil
		}
		out := d.StaffWifiDeviceReport(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// UserLogout
	fw.Post("/"+domain.UserLogoutAction, func(c *fiber.Ctx) error {
		in := domain.UserLogoutIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.UserLogoutAction); err != nil {
			return nil
		}
		out := d.UserLogout(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// UserProfile
	fw.Post("/"+domain.UserProfileAction, func(c *fiber.Ctx) error {
		in := domain.UserProfileIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.UserProfileAction); err != nil {
			return nil
		}
		out := d.UserProfile(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// UserSessionKill
	fw.Post("/"+domain.UserSessionKillAction, func(c *fiber.Ctx) error {
		in := domain.UserSessionKillIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.UserSessionKillAction); err != nil {
			return nil
		}
		out := d.UserSessionKill(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// UserSessionsActive
	fw.Post("/"+domain.UserSessionsActiveAction, func(c *fiber.Ctx) error {
		in := domain.UserSessionsActiveIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.UserSessionsActiveAction); err != nil {
			return nil
		}
		out := d.UserSessionsActive(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

	// UserUpdateProfile
	fw.Post("/"+domain.UserUpdateProfileAction, func(c *fiber.Ctx) error {
		in := domain.UserUpdateProfileIn{}
		if err := webApiParseInput(c, &in.RequestCommon, &in, domain.UserUpdateProfileAction); err != nil {
			return nil
		}
		out := d.UserUpdateProfile(&in)
		return in.ToFiberCtx(c, out, &out.ResponseCommon, in)
	})

}

// Code generated by 1_codegen_test.go DO NOT EDIT.
