package presentation

import (
	"github.com/gofiber/fiber/v2"
	"github.com/kokizzu/gotro/M"
)


// Code generated by 1_codegen_test.go DO NOT EDIT.


var viewList = map[string]string{
	`AdminBookingLogs`: `../svelte/admin/bookingLogs.html`, // ../svelte/admin/bookingLogs.svelte
	`AdminBuildingLogs`: `../svelte/admin/buildingLogs.html`, // ../svelte/admin/buildingLogs.svelte
	`AdminFacilityLogs`: `../svelte/admin/facilityLogs.html`, // ../svelte/admin/facilityLogs.svelte
	`AdminLocationLogs`: `../svelte/admin/locationLogs.html`, // ../svelte/admin/locationLogs.svelte
	`AdminPaymentLogs`: `../svelte/admin/paymentLogs.html`, // ../svelte/admin/paymentLogs.svelte
	`AdminRoomLogs`: `../svelte/admin/roomLogs.html`, // ../svelte/admin/roomLogs.svelte
	`AdminSettingFixInconsistencies`: `../svelte/admin/settingFixInconsistencies.html`, // ../svelte/admin/settingFixInconsistencies.svelte
	`AdminTenantLogs`: `../svelte/admin/tenantLogs.html`, // ../svelte/admin/tenantLogs.svelte
	`AdminUserLogs`: `../svelte/admin/userLogs.html`, // ../svelte/admin/userLogs.svelte
	`AdminWifiDeviceLogs`: `../svelte/admin/wifiDeviceLogs.html`, // ../svelte/admin/wifiDeviceLogs.svelte
	`AdminBooking`: `../svelte/adminBooking.html`, // ../svelte/adminBooking.svelte
	`AdminBuilding`: `../svelte/adminBuilding.html`, // ../svelte/adminBuilding.svelte
	`AdminFacility`: `../svelte/adminFacility.html`, // ../svelte/adminFacility.svelte
	`AdminLocation`: `../svelte/adminLocation.html`, // ../svelte/adminLocation.svelte
	`AdminPayment`: `../svelte/adminPayment.html`, // ../svelte/adminPayment.svelte
	`AdminRoom`: `../svelte/adminRoom.html`, // ../svelte/adminRoom.svelte
	`AdminTenants`: `../svelte/adminTenants.html`, // ../svelte/adminTenants.svelte
	`AdminUsersManagement`: `../svelte/adminUsersManagement.html`, // ../svelte/adminUsersManagement.svelte
	`AdminWifiDevice`: `../svelte/adminWifiDevice.html`, // ../svelte/adminWifiDevice.svelte
	`Debug`: `../svelte/debug.html`, // ../svelte/debug.svelte
	`Error`: `../svelte/error.html`, // ../svelte/error.svelte
	`Index`: `../svelte/index.html`, // ../svelte/index.svelte
	`StaffBooking`: `../svelte/staffBooking.html`, // ../svelte/staffBooking.svelte
	`StaffMissingDataReport`: `../svelte/staffMissingDataReport.html`, // ../svelte/staffMissingDataReport.svelte
	`StaffOccupancyHeatmap`: `../svelte/staffOccupancyHeatmap.html`, // ../svelte/staffOccupancyHeatmap.svelte
	`StaffOccupancyReport`: `../svelte/staffOccupancyReport.html`, // ../svelte/staffOccupancyReport.svelte
	`StaffPricePerDayReport`: `../svelte/staffPricePerDayReport.html`, // ../svelte/staffPricePerDayReport.svelte
	`StaffRevenueReport`: `../svelte/staffRevenueReport.html`, // ../svelte/staffRevenueReport.svelte
	`StaffTenants`: `../svelte/staffTenants.html`, // ../svelte/staffTenants.svelte
	`StaffWifiDeviceReport`: `../svelte/staffWifiDeviceReport.html`, // ../svelte/staffWifiDeviceReport.svelte
	`User`: `../svelte/user.html`, // ../svelte/user.svelte
}


func (v *Views) RenderAdminBookingLogs(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminBookingLogs`].Str(m))
}

func (v *Views) RenderAdminBuildingLogs(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminBuildingLogs`].Str(m))
}

func (v *Views) RenderAdminFacilityLogs(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminFacilityLogs`].Str(m))
}

func (v *Views) RenderAdminLocationLogs(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminLocationLogs`].Str(m))
}

func (v *Views) RenderAdminPaymentLogs(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminPaymentLogs`].Str(m))
}

func (v *Views) RenderAdminRoomLogs(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminRoomLogs`].Str(m))
}

func (v *Views) RenderAdminSettingFixInconsistencies(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminSettingFixInconsistencies`].Str(m))
}

func (v *Views) RenderAdminTenantLogs(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminTenantLogs`].Str(m))
}

func (v *Views) RenderAdminUserLogs(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminUserLogs`].Str(m))
}

func (v *Views) RenderAdminWifiDeviceLogs(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminWifiDeviceLogs`].Str(m))
}

func (v *Views) RenderAdminBooking(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminBooking`].Str(m))
}

func (v *Views) RenderAdminBuilding(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminBuilding`].Str(m))
}

func (v *Views) RenderAdminFacility(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminFacility`].Str(m))
}

func (v *Views) RenderAdminLocation(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminLocation`].Str(m))
}

func (v *Views) RenderAdminPayment(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminPayment`].Str(m))
}

func (v *Views) RenderAdminRoom(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminRoom`].Str(m))
}

func (v *Views) RenderAdminTenants(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminTenants`].Str(m))
}

func (v *Views) RenderAdminUsersManagement(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminUsersManagement`].Str(m))
}

func (v *Views) RenderAdminWifiDevice(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`AdminWifiDevice`].Str(m))
}

func (v *Views) RenderDebug(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`Debug`].Str(m))
}

func (v *Views) RenderError(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`Error`].Str(m))
}

func (v *Views) RenderIndex(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`Index`].Str(m))
}

func (v *Views) RenderStaffBooking(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`StaffBooking`].Str(m))
}

func (v *Views) RenderStaffMissingDataReport(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`StaffMissingDataReport`].Str(m))
}

func (v *Views) RenderStaffOccupancyHeatmap(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`StaffOccupancyHeatmap`].Str(m))
}

func (v *Views) RenderStaffOccupancyReport(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`StaffOccupancyReport`].Str(m))
}

func (v *Views) RenderStaffPricePerDayReport(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`StaffPricePerDayReport`].Str(m))
}

func (v *Views) RenderStaffRevenueReport(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`StaffRevenueReport`].Str(m))
}

func (v *Views) RenderStaffTenants(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`StaffTenants`].Str(m))
}

func (v *Views) RenderStaffWifiDeviceReport(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`StaffWifiDeviceReport`].Str(m))
}

func (v *Views) RenderUser(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(v.cache[`User`].Str(m))
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
